#!/bin/bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# install_hooks.sh — Idempotent Git pre-commit hook installer.
#
# Installs a thin shim at .git/hooks/pre-commit that calls tools/check_secrets.sh
# to scan staged changes for exposed API keys, passwords, and other secrets.
# Run this once after cloning: bash tools/install_hooks.sh

set -e

# Find git repo root
GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
  echo "❌ ERROR: Not in a git repository"
  exit 1
}

HOOKS_DIR="$GIT_ROOT/.git/hooks"
HOOK_FILE="$HOOKS_DIR/pre-commit"
CHECK_SECRETS="$GIT_ROOT/tools/check_secrets.sh"

# Verify check_secrets.sh exists
if [ ! -f "$CHECK_SECRETS" ]; then
  echo "❌ ERROR: tools/check_secrets.sh not found at $CHECK_SECRETS"
  exit 1
fi

# Create .git/hooks directory if missing
if [ ! -d "$HOOKS_DIR" ]; then
  mkdir -p "$HOOKS_DIR"
fi

# Backup existing pre-commit hook if present (and not our shim)
if [ -f "$HOOK_FILE" ]; then
  # Check if it's our shim (contains our sentinel comment)
  if ! grep -q "install_hooks.sh" "$HOOK_FILE" 2>/dev/null; then
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="$HOOK_FILE.bak.$TIMESTAMP"
    mv "$HOOK_FILE" "$BACKUP_FILE"
    echo "⚠️  Backed up existing pre-commit hook to $BACKUP_FILE"
  fi
fi

# Create the hook shim
cat > "$HOOK_FILE" << 'HOOK_EOF'
#!/bin/bash
# Generated by tools/install_hooks.sh — do not edit by hand.
# This shim calls tools/check_secrets.sh to scan staged changes for secrets.

set -e
GIT_ROOT=$(git rev-parse --show-toplevel)
exec bash "$GIT_ROOT/tools/check_secrets.sh"
HOOK_EOF

# Set executable permission
chmod +x "$HOOK_FILE"

echo "✓ pre-commit hook installed at $HOOK_FILE"
echo "  This hook will run tools/check_secrets.sh on all staged changes."
echo "  To bypass (not recommended): git commit --no-verify"
